/options:
  get:
    tags:
      - 'test'
    summary: Returns a list of options.
    description: ''
    responses:
      200:
        description: A JSON array of options
        content:
          application/json:
            schema:
              type: object
              properties:
                options:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
      default:
        $ref: '#components/responses/DefaultErrors'
